# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c68040e9d6f527a1bc4b36897c4ed085675b97bf788dd375682d1f70db5216554ee70ba11f015c32b982a964fc422a9d6d1b319101e33b6b720a3ec811993b36

test:
  secret_key_base: 017e3f817dc709cfa69cefefdfa39070d7e75efe09415546126b4eacc04813dbf096c4a24e125f235b10e9f305bbae0d5c56dbf2a491216b9d368dd2b3f635a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
